packages:
  - .

allowBuilds:
  esbuild: false
  protobufjs: false
  unrs-resolver: false

blockExoticSubdeps: true

minimumReleaseAge: 10080 # 7 days in minutes
minimumReleaseAgeExclude:
  - '@typescript/*'
  - fast-xml-builder@1.1.7

overrides:
  eslint-import-resolver-typescript: '^4.4.4'
  fast-xml-builder@<=1.1.6: ^1.1.7
  semver: '>=7'
  uuid: ^14.0.0

strictPeerDependencies: false

trustPolicy: no-downgrade
