packages:
  - .

onlyBuiltDependencies:
  - protobufjs

overrides:
  '@eslint/eslintrc>ajv': ^6.12.4
  '@eslint/js': ^9
  '@stylistic/eslint-plugin': '>=5.0.0'
  ajv@<8.18.0: '>=8.18.0'
  eslint: ^9
  eslint>ajv: ^6.12.4
  fast-xml-parser@<5.3.8: '>=5.3.8'
  fast-xml-parser@>=4.1.3 <5.3.6: '>=5.3.6'
  minimatch@<10.2.1: '>=10.2.1'
