packages:
  - .

allowBuilds:
  esbuild: false
  protobufjs: false
  unrs-resolver: false

blockExoticSubdeps: true

minimumReleaseAge: 10080 # 7 days in minutes
minimumReleaseAgeExclude:
  - '@typescript/*'
  - '@opentelemetry/core@2.8.0'

overrides:
  '@opentelemetry/core@<2.8.0': ^2.8.0
  esbuild@>=0.17.0 <0.28.1: ^0.28.1
  esbuild@>=0.27.3 <0.28.1: ^0.28.1
  eslint-import-resolver-typescript: '^4.4.5'
  semver: '>=7'
  uuid: ^14.0.1

strictPeerDependencies: false

trustPolicy: no-downgrade
